# Each of the following keygroups/key value pairs should produce an error. Uncomment to them to test

[error]   ïƒ ¥ôú δïδñ'ƭ çáƭçλ ƭλïƨ, ¥ôúř ƥářƨèř ïƨ βřôƙèñ
string = "Âñ¥ƭλïñϱ ôƭλèř ƭλáñ ƭáβƨ, ƨƥáçèƨ áñδ ñèωℓïñè áƒƭèř á ƙè¥ϱřôúƥ ôř ƙè¥ Ʋáℓúè ƥáïř λáƨ èñδèδ ƨλôúℓδ ƥřôδúçè áñ èřřôř úñℓèƨƨ ïƭ ïƨ á çô₥₥èñƭ"   ℓïƙè ƭλïƨ

array = [
         "Tλïƨ ₥ïϱλƭ ₥ôƨƭ ℓïƙèℓ¥ λáƥƥèñ ïñ ₥úℓƭïℓïñè ářřá¥ƨ",
         £ïƙè λèřè,
         "ôř λèřè,
         áñδ λèřè"
         ]     Éñδ ôƒ ářřá¥ çô₥₥èñƭ, ƒôřϱôƭ ƭλè #
number = 3.14 ƥï <--áϱáïñ ƒôřϱôƭ ƭλè #       