    
[ hello  ] # lol
a =    2#3
b = "hello world"

[ bob. "something" ]
flt7 = 6.626e-34
bool = false # it's true though!
arr = [ 1, 2   ,    3 
,]

inline = { alice = "some", key = 2 }

multi = """\
Hello World!
This is \"multiline\"!\
"""

date1 = 1979-05-27T07:32:00Z
date2 = 1979-05-27T00:32:00-07:00
date3 = 1979-05-27T00:32:00.999999-07:00

